[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
startCommand = "npm start"

[services.web]
tcpProxyApplicationPort = 5000